---
title: Customization
---

## Specific Learning Goals
This class is intended to provide useful skills for your ongoing research.
Review types of fisheries-independent surveys and survey data products for ecosystem processes research, ecological studies, stock assessment, and forecasting within these disciplines.
Learn principles of sampling and survey designs, survey logistics and management, and survey data product estimation and application.
Analyze fishery-independent survey data using various statistical methods.
Plan research in survey science topics, e.g. uncertainty (observation error), survey continuity (catchability), effort optimization, flexible survey design, model-based estimators, simulations, statistical tools and new technology.
Complete a research project using survey data.
Learn concepts and tools for long-term strategic planning of surveys, including adapting monitoring programs to our changing ecosystems as species distributions shift due to environmental change and ecological interactions. 
Course Material
No required text. Course materials will be selected from journals, books, and other published scientific literature. These will be available as PDFs through the course website. Materials will be divided into required and optional. 
Course Format
Lectures: Lectures will take up approximately half of the in-class time. There will be two to three lectures per week given by instructors or visiting experts. Lectures will focus on a range of topics, described with examples from different survey programs around the world. Lecture slides will be made available on the course website for downloading and reviewing.
Literature review and discussion sections: Students (in groups of 1-3) will be responsible for presentations on relevant literature and leading subsequent discussions in-class. Approximately one-quarter of in-class time will be used for these presentations and discussions of scientific papers. Students (in groups of 1-3) will be responsible for presentations on relevant literature and leading subsequent discussion. Presentations will include a summary of relevant scientific papers on a chosen survey-related topic and all Sstudents will be expected to actively participate in discussions. List of papers for student presentations and discussion will be provided by instructors, but students will be given the opportunity to propose a paper of their choice for presentations. The point of the discussion section is to read peer-reviewed literature and become familiar with current topics in survey science.
Survey data analysis: Each student will be responsible for one mid-course project to include survey data analysis on a data set of their choice (data sets from several actual surveys will be available, as needed). Analysis can involve estimation of standard design-based or model-based survey data products or could involve custom analysis for class projects.
Research plan and final paper: Half of the student grade is based on a final written research paper using survey data. Topics for the final paper will be proposed by students and will be presented for class discussion and feedback within the first 3 weeks of the quarter.

GRADING 
Students will be graded on 4 tasks:
1. Project plan - 1 page and 5 min presentation (10% weight)
DUE: Presentation January 14
Within the first days of the quarter students will be responsible for planning a research project. Students can propose a project of their choice as long as the data for the project is of survey origin. Project plans should be discussed with and accepted by instructors. Once accepted students will be responsible for writing a 1 page project plan and for presentation of the plan during the class. Instructors and students will provide feedback on the plan during the class discussion. 
2. Literature review 20-30 min presentation on the survey topic (20%)
DUE: Presentation February 9
Students will be responsible for presentations on relevant literature and leading subsequent discussion. Literature review presentations will be conducted on Feb 9 or later depending on the number of presentations. Papers for this literature review should be relevant to the final  project. Students are advised to discuss potential papes for this review with instructors, but students will be given the opportunity to propose a paper(s) of their choice for presentations. Literature review presentation will be followed by Q & A session and in-class discussion on the presented topics
3. Survey data analysis (20%)
DUE: 16 February
Survey data analysis will involve estimation of standard design-based and model-based survey data products (from provided “true distributions”) or could involve custom analysis of survey data used for class projects. Format of the analysis presentation will be open and can include analysis description and graphs or tables. Analysis will be graded separately, but can be included as part of the final paper or as an independent document. Data analysis will be due at the end of week 6 of the course.  
4. Final project - up to 5-8 pages and 20-30 min presentation (50%)
Due: Presentation March 4-11; Paper March 13
Final project results will be presented in the form of 20-30 minutes in-class PPT presentation. Students will receive feedback from instructors and time for in-class discussion will be provided. Presentations will occur during the last 2 weeks of the course. Final 5 - 8 page paper will be due at the end of week 10 and graded during the week of finals.

## Grading Scale

[Grading scale](https://grad.uw.edu/policies-procedures/graduate-school-memoranda/memo-19-grading-system-for-graduate-students/)

```{r}
data.frame(
  stringsAsFactors = FALSE,
           Percent = c("GPA","Letter","Percent",
                       "GPA","Letter","Percent","GPA","Letter","≥95","4","A",
                       "86","3.1","77","2.2","94","3.9","85","3","B",
                       "76","2.1","93","3.8","A-","84","2.9","75","2",
                       "C","92","3.7","83","2.8","B-","74","1.9","91",
                       "3.6","82","2.7","B-","73","1.8","90","3.5","81",
                       "2.6","72","1.7","89","3.4","B+","80","2.5","<72",
                       "1.6- 0.0","E","88","3.3","79","2.4","C+","87",
                       "3.2","78","2.3")
)
```
## Lecture plan 



Week
Date
Lecture
Instructor
Description
1
Jan 5
1
Kotwicki (Wassermann)
Course outline and introductions. Overview of fisheries dependent and independent data collection, types of fisheries surveys, and other survey science topics. Describe potential class project. Provide examples.
Guest Lectures: Lyle Britt (AFSC), Denise McKelvey (AFSC)
Jan 7
2
Kotwicki (Markowitz)
Overview of survey data products for ecosystem processes research, ecological studies, stock assessment, and forecasting. 
Guest Lectures: Kayla Ualesi (IPHC), Ebett Siddon (NOAA)
2
Jan 12
3
Barnett (Markowitz)
Guest presentation. Design principles, sampling designs, logistics and estimation. (Ray Webster) 
Guest presentation. Case study for implementing survey design (Zack Oyafuso).
Jan 14
4
Kotwicki (Markowitz)
Student presentations on project plan: 5 minutes presentation, 5-10 minutes for discussion.
Some general topics
a.       Design of a new survey from the ground up.
b.       Analysis of existing survey data (e.g. present survey data product and its uncertainty, use of survey data in assessments, role of uncertainty in assessment).
c.       Literature review of a survey topic under active research.

Examples of literature overview. Opportunity for students to ask questions about class projects.
3
Jan 19




Martin Luther King Jr. Observed Holiday
Jan 21
5
Kotwicki (Wassermann)
Overview of current hot topics in survey science: Uncertainty (observation error), Survey continuity (flexibility and catchability), multispecies optimisation, flexible survey design, model-based estimation of survey data products, simulations, statistical tools and new technology. Combining surveys. Absolute indices of abundance (catchability). Changes in technology affect continuity but also improve estimates. Using observation from fishing vessels.

Second part of the class will consist of discussion topics picked by students after the lecture. We will pick 4 topics of interest to students, prioritize  them and discuss them in detail.
4
Jan 26
6
Hicks (Markowitz)
Examples of combining surveys into one platform and/or combining different data types across platforms to improve survey products. Combining acoustic/trawl data and integrating NW and SW acoustic surveys.
Main topics: changes to survey, calibration, scientific and legal process.  
Guest Lectures: Cole Monnahan/Derek BolserJulia Clemons (NWFSC)
Jan 28
7
Hicks (Wassermann)
General considerations for using survey data in stock assessments and a few examples from recent assessments. 
Guest Lecture: Ian Stewart/Allan Hicks (IPHC)
5
Feb 2
8
Barnett (Markowitz)
Model-based approaches for standardizing both abundance and compositional data. 
Guest Lecture: Eric Ward (NWFSC)
Feb 4
9
Barnett (Wassermann)
Student data simulation and analysis with design- and model-based approaches 
6
Feb 9
10
Kotwicki (Markowitz)
Student Led Literature Review (20min/10min)
Feb 11
11
Kotwicki (Wassermann)
Explore total variance of a survey, sources of error, estimation methods, minimizing error, and sampling effort optimization. Survey design planning in a changing environment.
7
Feb 16




President’s Day Observed Holiday
Feb 18
12
Hicks (Wassermann)
Acoustic Techniques for Fishery and Ecosystem Surveys
Guest Lecture: John Horne (UW/SAFS)

Engaging Industry 
Guest Lecture: John Gauvin, John Harms
8
Feb 23
13
Kotwicki (Markowitz)
International perspective
Guests & panel discussion: Richard O’Driscoll (NIWA), Olav Rune Godø (IMR Norway - retired), Mark Dickey-Collas (ICES)
Feb 25
14
Hicks (Wassermann)
Advanced Technologies. Platforms, technologies and provision of data for stock assessment. 
Guests + panel discussion: Alex De Robertis (AFSC), Kresimir Williams (AFSC), Ole Shelton (NWFSC)
9
Mar 2


Kotwicki (Markowitz)
Future of surveys (Kotwicki)
Mar 4


Barnett (Wassermann)
Student Presentations
10
Mar 9


Hicks (Markowitz)
Student Presentations
Mar 11


Kotwicki (Wassermann)
Student Presentations
Class Evaluation URL: https://uw.iasystem.org/survey/268860



## Academic integrity

Plagiarism, cheating, and other misconduct are serious violations of your contract as a  student. I expect that you will know and follow the University's policies on cheating and  plagiarism. Any suspected cases of academic misconduct will be handled according to  University regulations. More information can be found  
at: https://depts.washington.edu/grading/pdf/AcademicResponsibility.pdf 

For this course, plagiarism is defined as figures and legends that are identical or eerily  similar to those of other students. You should absolutely work together, get advice and  tips from other students, and help each other (this is the essence of being a successful  and helpful scientist), but the final project must be your own work.  
## Religious accommodation policy

Washington state law requires that UW develop a policy for accommodation of student  absences or significant hardship due to reasons of faith or conscience, or for organized  religious activities. The UW’s policy, including more information about how to request an  accommodation, is available at Religious Accommodations Policy. Accommodations 
must be requested within the first two weeks of this course using the Religious  Accommodations Request form.

## Disability accommodations

To request academic accommodations due to a disability, please contact Disability Resources for Students, 448 Schmitz, (206)543-8924 (V/TTY). If you have a letter from Disability Resources for Students indicating that you have a disability which requires academic accommodations, please present the letter to the instructor so we can discuss the accommodations needed for this class.
